{% block PROXY_COMMANDS %}
{{ "command:"|indent(8, true) + "|"|indent(32, true) }}
{{ "-cookie-secure=false"|indent(10, true) }}
{%- if (SERVICES[service]['networks'] and SERVICES[service]['networks']['vpn'] and SERVICES[service]['ports'] %}
{{ "-upstream=http://"|indent(10, true) + VPN_CONTAINER|lower|replace("_", "-") + ":" + SERVICES[service]['ports'][0].split(':')[1] }}
{%- elif SERVICES[service]['ports']  %}
{{ "-upstream=http://"|indent(10, true) + SERVICE)|lower|replace("_", "-") + ":80" }}
{%- endif %}
{{ "-authenticated-emails-file=/file/authenticated-emails.txt"|indent(10, true) }}
{{ "-email-domain=gmail.com"|indent(10, true) }}
{{ "-http-address=http://0.0.0.0:"|indent(10, true) + OAUTH_PORT }}
{{ "-provider=github"|indent(10, true) }}
{%- if 'subdomains' in SERVICES[service] and SERVICES[service]['subdomains'] %}
{{ "-redirect-url=https://"|indent(10, true) + SERVICES[service]['subdomains'][0] + "." + DOMAIN) }}
{%- else %}
{{ "-redirect-url=https://"|indent(10, true) + SERVICE|lower + "." + DOMAIN }}
{{ super() }}
{%- endif %}
{% endblock %}
