{% block NETWORK_GLOBALS %}
{{ "networks:" }}
{{ "shared-backend:"|indent(4,true) }}
{{ "external:" |indent(8,true) + "True"|indent(32,true) }}
{{ "backend:"|indent(4,true) }}
{{ "driver:"|indent(8,true) + "bridge"|indent(34,true) }}
{{ "ipam:"|indent(8,true) }}
{{ "config:"|indent(12, true) }}
{{ "- subnet:"|indent(14,true) +  BACKEND_SUBNET|indent(26,true) }}
{{ "frontend:"|indent(4,true) }}
{{ "external:" |indent(8,true) + "True"|indent(32,true) }}
{{ super() }}
{% endblock %}
